//
// Created by Cain Martin on 2024/12/12.
//

#ifndef KITEN_ENGINE_DIRECTIONALLIGHTCOMPONENT_H
#define KITEN_ENGINE_DIRECTIONALLIGHTCOMPONENT_H


class DirectionalLightComponent
{

};


#endif //KITEN_ENGINE_DIRECTIONALLIGHTCOMPONENT_H
